# -*- coding: utf-8 -*-
"""social_scam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HTnfWiVp7IpBRbKdKzEgisHgiq9AZ71
"""

!pip install pandas scikit-learn nltk transformers datasets torch joblib

!pip install pandas scikit-learn nltk transformers datasets torch joblib

import pandas as pd

fake1 = pd.read_csv("gossipcop_fake.csv")
real1 = pd.read_csv("gossipcop_real.csv")

fake2 = pd.read_csv("politifact_fake.csv")
real2 = pd.read_csv("politifact_real.csv")

fake1["label"] = 1
fake2["label"] = 1

real1["label"] = 0
real2["label"] = 0

df = pd.concat([fake1, real1, fake2, real2], ignore_index=True)

print(df.shape)
df.head()

df["content"] = df["title"]

import re
import nltk
from nltk.corpus import stopwords

# Ensure NLTK stopwords are downloaded
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    # Remove URLs
    text = re.sub(r'http\S+', '', text)
    # Remove non-alphabetic characters
    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()
    # Filter out stopwords
    words = [w for w in words if w not in stop_words]

    return ' '.join(words)

df['clean_text'] = df['content'].apply(clean_text)

from sklearn.model_selection import train_test_split

X = df["clean_text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

from sklearn.svm import SVC

svm_model = SVC(probability=True)

svm_model.fit(X_train_vec, y_train)

from sklearn.metrics import accuracy_score, classification_report

svm_pred = svm_model.predict(X_test_vec)

print("SVM Accuracy:", accuracy_score(y_test, svm_pred))

print(classification_report(y_test, svm_pred))

!pip install datasets

from datasets import Dataset

from datasets import Dataset

data = pd.DataFrame({
    "text": df["clean_text"],
    "label": df["label"]
})

train_df, test_df = train_test_split(data, test_size=0.2, random_state=42)

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize(example):
    return tokenizer(
        example["text"],
        padding="max_length",
        truncation=True,
        max_length=256
    )

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset = train_dataset.remove_columns(["text", "__index_level_0__"])
test_dataset = test_dataset.remove_columns(["text", "__index_level_0__"])

train_dataset.set_format("torch")
test_dataset.set_format("torch")

from transformers import BertForSequenceClassification

model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
)

import numpy as np
from sklearn.utils.class_weight import compute_class_weight
import torch

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(df["label"]),
    y=df["label"]
)

class_weights = torch.tensor(class_weights, dtype=torch.float)

print(class_weights)

from transformers import TrainingArguments

training_args = TrainingArguments(

    output_dir="./results",

    learning_rate=2e-5,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,

    num_train_epochs=5,

    eval_strategy="epoch",
    save_strategy="epoch"
)

from transformers import Trainer

trainer = Trainer(

    model=model,
    args=training_args,

    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

trainer.train()

trainer.evaluate()

predictions = trainer.predict(test_dataset)

preds = predictions.predictions.argmax(axis=1)

labels = predictions.label_ids

accuracy = accuracy_score(labels, preds)

print("BERT Accuracy:", accuracy)

model.save_pretrained("bert_scam_model")
tokenizer.save_pretrained("bert_scam_model")

!zip -r bert_scam_model.zip bert_scam_model

from google.colab import files
files.download("bert_scam_model.zip")